services:
  giliover-session:
    container_name: giliover-session
    image: giliover-session
    stdin_open: true
    privileged: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/$UID/pulse/native
    build:
      context: .
      dockerfile: ./Dockerfile.session
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/$UID/pulse:/run/user/$UID/pulse
      - /dev/snd:/dev/snd
    devices:
      - /dev/snd
    restart: no